#!/bin/bash

#
echo "please enter username : "
read -s USERNAME #THE VALUE ENTER ABOVE WILL BE ATOMATICALLY ATTECHED TO USERNAME VARIABLE .
echo "please enter userpassword: "
read -s USERPASSWORD  #THE VALE ENTER ABOVE WILL BE AUTOMATICALLY ATTECHE TO USERPASSWORD VARIABLE.
